---
kind: pipeline
type: docker
name: default

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
      - ./dl

- name: createimage
  image: docker:latest
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock
  commands:
  - ls -l ./
  - ls -l /var/run/
  - docker build -t breadbee_buildroot .
  - chmod -R o+rw ./

- name: secrets
  image: breadbee_buildroot
  pull: if-not-exists
  environment:
    SSH_KEY:
      from_secret: tftp_ssh_key
  commands:
    - mkdir ./secrets/ && echo "$SSH_KEY" > ./secrets/tftp_ssh_key && chmod 0600 ./secrets/tftp_ssh_key

- name: bootstrap
  image: breadbee_buildroot
  pull: if-not-exists
  commands:
  - make bootstrap

- name: download
  image: breadbee_buildroot
  pull: if-not-exists
  commands:
  - make buildroot-dl
  - make buildroot-rescue-dl

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
      - ./dl

- name: main
  image: breadbee_buildroot
  pull: if-not-exists
  commands:
  - make buildroot

- name: rescue
  image: breadbee_buildroot
  pull: if-not-exists
  commands:
  - make buildroot-rescue

- name: upload
  image: breadbee_buildroot
  pull: if-not-exists
  commands:
  - make upload

volumes:
  - name: cache
    host: 
      path: /tmp/cache
  - name: docker_sock
    host:
      path: /var/run/docker.sock

...
