version: 2.1

jobs:
  build:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run:
          command: apt-get -qq update
      - run:
          command: apt-get -qq install build-essential file wget cpio python unzip rsync bc git
      - run:
          command: make bootstrap
      - run:
          environment:
            FORCE_UNSAFE_CONFIGURE: 1
          command: make

workflows:
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
