version: 2.1

jobs:
  build:
    docker:
      - image: debian:latest
    steps:
      - checkout
      - run:
          command: apt-get install build-essential
      - run:
          command: make

workflows:
  main:
    jobs:
      - build
